# Generated by Django 5.0 on 2023-12-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                default=38096063, max_length=30, verbose_name="phone number"
            ),
            preserve_default=False,
        ),
    ]
