# Generated by Django 5.0 on 2023-12-22 19:41

import ckeditor.fields
import django.db.models.deletion
import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=mainapp.models.content_file_name),
                ),
                ("slug", models.SlugField()),
                ("title", models.CharField(max_length=155)),
                ("subtitle", models.CharField(max_length=155)),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, verbose_name="Name of the category"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "vendor_code",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="TopCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, verbose_name="Name of the top category"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "category_icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=mainapp.models.content_file_name,
                    ),
                ),
            ],
            options={
                "verbose_name": "Top Category",
                "verbose_name_plural": "Top Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("product_code", models.IntegerField(verbose_name="Product Code")),
                ("price", models.IntegerField(verbose_name="Price")),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "qty_product",
                    models.IntegerField(default=0, verbose_name="Quantity of product"),
                ),
                (
                    "ordered",
                    models.IntegerField(default=0, verbose_name="Ordered times"),
                ),
                (
                    "popular",
                    models.IntegerField(default=0, verbose_name="Viewed times"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="images/product/")),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="top_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.topcategory",
                verbose_name="Parent category",
            ),
        ),
    ]
