# Generated by Django 4.2 on 2023-12-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="popular",
            new_name="views",
        ),
    ]
