# Generated by Django 4.2 on 2023-12-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_rename_popular_product_views"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Banner",
        ),
        migrations.RemoveField(
            model_name="category",
            name="vendor_code",
        ),
    ]
