# Generated by Django 4.1 on 2024-03-25 11:37

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_delete_banner_remove_category_vendor_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to=mainapp.models.product_image_file_path
            ),
        ),
    ]
