# Generated by Django 4.1 on 2024-03-25 14:09

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_productimage_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topcategory",
            name="category_icon",
            field=models.ImageField(
                blank=True, null=True, upload_to=mainapp.models.content_file_name
            ),
        ),
    ]
